["run_parameters"]
task = "regression"
debug = true
n_splits = [2]
test_size = 0.2
split_kind = "group_shuffle"


["join_parameters"]
join_strategy = "left"
aggregation = ["first"]

["evaluation_models"]
chosen_model = ["ridgecv"]
catboost.iterations = 300
catboost.od_type = "Iter"
catboost.od_wait = 10
catboost.l2_leaf_reg = 0.01
catboost.thread_count = 32

["estimators"]
no_join.active = true
highest_containment.active = true
full_join.active = true

top_k_full_join.active = false
top_k_full_join.top_k = 1

best_single_join.active = true
best_single_join.use_rf = false

stepwise_greedy_join.active = true
stepwise_greedy_join.budget_type = "iterations"
stepwise_greedy_join.budget_amount = [30]
stepwise_greedy_join.epsilon = [0.0]
stepwise_greedy_join.ranking_metric = "containment"
stepwise_greedy_join.use_rf=false

#### Exact matching
# Company employees
[["query_cases"]]
top_k = 30
join_discovery_method = "exact_matching"
data_lake = "open_data_us"
table_path = "data/source_tables/open_data_us/company_employees-depleted_name-open_data.parquet"
query_column = "name"
