["run_parameters"]
task = "regression"
debug = false
n_splits = [1]
test_size = 0.2
split_kind = "group_shuffle"

["join_parameters"]
join_strategy = "left"
aggregation = ["first"]

["evaluation_models"]
chosen_model = ["ridgecv"]
catboost.iterations = 300
catboost.od_type = "Iter"
catboost.od_wait = 10
catboost.l2_leaf_reg = 0.01
catboost.thread_count = 32

["estimators"]
# Activation
no_join.active = true
top_k_full_join.active = false
best_single_join.active = true
best_single_join.use_rf = false
full_join.active = true
stepwise_greedy_join.active = true
stepwise_greedy_join.use_rf = false
highest_containment.active=true
# Parameters
top_k_full_join.top_k = 5
stepwise_greedy_join.budget_type = "iterations"
stepwise_greedy_join.budget_amount = [2]
stepwise_greedy_join.epsilon = [0.0]
stepwise_greedy_join.ranking_metric = "containment"

#### Exact matching
# Housing prices
[["query_cases"]]
top_k = 10
join_discovery_method = "exact_matching"
data_lake = "open_data_us"

table_path = "data/source_tables/open_data_us/housing_prices-depleted_County-open_data.parquet"
query_column = "County"


# US elections
[["query_cases"]]
top_k = 10
join_discovery_method = "exact_matching"
data_lake = "open_data_us"

table_path = "data/source_tables/open_data_us/us_elections-depleted_county_name-open_data.parquet"
query_column = "county_name"

# US Accidents
[["query_cases"]]
data_lake = "open_data_us"
join_discovery_method = "exact_matching"
table_path = "data/source_tables/open_data_us/us_accidents_2021-depleted-open_data_County.parquet"
query_column = "County"
top_k = 10

# US Accidents large
[["query_cases"]]
data_lake = "open_data_us"
join_discovery_method = "exact_matching"
table_path = "data/source_tables/open_data_us/us_accidents_large-depleted-open_data_County.parquet"
query_column = "County"
top_k = 10
